export const COMPILED_CONTRACT_LOAD = "COMPILED_CONTRACT_LOAD";
export const COMPILED_CONTRACT_ERROR = "COMPILED_CONTRACT_ERROR";
export const COMPILED_CONTRACT_DEPLOYED = "COMPILED_CONTRACT_DEPLOYED";
export const COMPILED_CONTRACT_DEPLOYING = "COMPILED_CONTRACT_DEPLOYING";

export const CONTRACTS_ADD = "CONTRACTS_ADD";
export const CONTRACTS_REMOVE = "CONTRACTS_REMOVE";
export const CONTRACTS_REMOVE_ALL = "CONTRACTS_REMOVE_ALL";

export const SIGNERS_ADD = "SIGNERS_ADD";
export const SIGNERS_CLEAR = "SIGNERS_CLEAR";
export const SIGNERS_SELECT = "SIGNERS_SELECT";
export const SIGNERS_BALANCE = "SIGNERS_BALANCE";

export const UTILS_SET_NOTIFY = "UTILS_SET_NOTIFY";
export const UTILS_SET_PROVIDER = "UTILS_SET_PROVIDER";
export const UTILS_SET_REEFSCAN_URL = "UTILS_SET_REEFSCAN_URL";