export const COMPILED_CONTRACT_LOAD = "COMPILED_CONTRACT_LOAD";
export const COMPILED_CONTRACT_ERROR = "COMPILED_CONTRACT_ERROR";
export const COMPILED_CONTRACT_DEPLOYED = "COMPILED_CONTRACT_DEPLOYED";
export const COMPILED_CONTRACT_DEPLOYING = "COMPILED_CONTRACT_DEPLOYING";

export const CONTRACTS_ADD = "CONTRACTS_ADD";
export const CONTRACTS_REMOVE = "CONTRACTS_REMOVE";
export const CONTRACTS_REMOVE_ALL = "CONTRACTS_REMOVE_ALL";

export const SIGNERS_LOAD = "SIGNERS_LOAD";
export const SIGNERS_BALANCE = "SIGNERS_BALANCE";

export const UTILS_SET_NOTIFY = "UTILS_SET_NOTIFY";