export const CONTRACT_LOAD = "CONTRACT_LOAD";

export const TRANSACTION_ADD_CONTRACT = "TRANSACTION_ADD_CONTRACT";
export const TRANSACTION_REMOVE_CONTRACT = "TRANSACTION_REMOVE_CONTRACT";
export const TRANSACTION_REMOVE_ALL_CONTRACT = "TRANSACTION_REMOVE_ALL_CONTRACT";